# Generated by Django 5.0.7 on 2024-08-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_end_date_alter_user_priority_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='point',
            field=models.IntegerField(default=1000, null=True),
        ),
    ]
