# Generated by Django 5.0.7 on 2024-07-25 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_user_card_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_ex',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
